require: rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
  - "vendor/**/*"
  - "**/tmp/**/*"
  - "**/db/schema.rb"
  - "**/bin/**/*"
  - "config/**/*"
Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false
